import { EventItem, PropItem, SlotItem } from "../../.vitepress/components/api-block/src/types";

export const modalProps: PropItem[] = [
  { name: "v-model", remark: "对话框是否可见",
    remarkEn: "Whether the modal is visible", type: ["Boolean"], default: false },
  { name: "is-method", remark: "是否通过函数式调用（内部使用）",
    remarkEn: "Whether opened via imperative API (internal)", type: ["Boolean"], default: false },
  {
    name: "type",
    remark: "对话框类型，影响标题图标样式",
    remarkEn: "Modal type; affects title icon style",
    type: ["String"],
    optional: ["info", "success", "warning", "error", "confirm"],
  },
  { name: "title", remark: "对话框标题",
    remarkEn: "Modal title", type: ["String"], default: "" },
  { name: "content", remark: "对话框内容文本",
    remarkEn: "Modal content text", type: ["String"] },
  { name: "width", remark: "对话框宽度",
    remarkEn: "Modal width", type: ["String", "Number"], default: "50%" },
  { name: "body-class", remark: "内容区域自定义样式类",
    remarkEn: "Custom class for the body area", type: ["String"] },
  { name: "border-radius", remark: "对话框圆角",
    remarkEn: "Modal border radius", type: ["String"], default: "8px" },
  { name: "center", remark: "是否垂直居中显示",
    remarkEn: "Whether vertically centered", type: ["Boolean"], default: false },
  { name: "show-border", remark: "是否显示边框",
    remarkEn: "Whether bordered", type: ["Boolean"], default: true },
  { name: "top", remark: "距离顶部的偏移量",
    remarkEn: "Offset from the top", type: ["String"], default: "0" },
  { name: "bottom", remark: "距离底部的偏移量",
    remarkEn: "Offset from the bottom", type: ["String"], default: "0" },
  { name: "mask-closable", remark: "点击遮罩是否关闭对话框",
    remarkEn: "Whether clicking the mask closes the modal", type: ["Boolean"], default: true },
  { name: "hide-header", remark: "是否隐藏头部区域",
    remarkEn: "Whether to hide the header", type: ["Boolean"], default: false },
  { name: "hide-footer", remark: "是否隐藏底部区域",
    remarkEn: "Whether to hide the footer", type: ["Boolean"], default: false },
  { name: "hide-close", remark: "是否隐藏关闭按钮",
    remarkEn: "Whether to hide the close button", type: ["Boolean"], default: false },
  { name: "fullscreen", remark: "是否全屏显示",
    remarkEn: "Whether fullscreen", type: ["Boolean"], default: false },
  { name: "ok-text", remark: "确认按钮文字",
    remarkEn: "OK button text", type: ["String"], default: "确认" },
  { name: "ok-btn-props", remark: "确认按钮属性，透传至 Button 组件",
    remarkEn: "OK button props, passed through to Button", type: ["Object"] },
  { name: "cancel-text", remark: "取消按钮文字",
    remarkEn: "Cancel button text", type: ["String"], default: "取消" },
  { name: "cancel-btn-props", remark: "取消按钮属性，透传至 Button 组件",
    remarkEn: "Cancel button props, passed through to Button", type: ["Object"] },
  { name: "hide-cancel", remark: "是否隐藏取消按钮",
    remarkEn: "Whether to hide the cancel button", type: ["Boolean"], default: false },
  { name: "hide-title-icon", remark: "是否隐藏标题图标",
    remarkEn: "Whether to hide title icon", type: ["Boolean"], default: false },
  {
    name: "on-before-ok",
    remark: "确认前的异步回调，返回 true 关闭对话框，返回 false 保持打开。按钮自动进入 loading 状态",
    remarkEn: "Async callback before confirm; return true to close, false to keep open. Button shows loading automatically",
    type: ["Function"],
  },
];

export const modalEvents: EventItem[] = [
  { name: "cancel", remark: "点击取消或关闭按钮时触发",
    remarkEn: "Triggered on cancel or close" },
  { name: "confirm", remark: "点击确认按钮后触发",
    remarkEn: "Triggered after confirm" },
];

export const modalSlots: SlotItem[] = [
  { name: "default", remark: "对话框内容区域",
    remarkEn: "Modal body content" },
  { name: "header", remark: "自定义头部区域",
    remarkEn: "Custom header" },
  { name: "footer", remark: "自定义底部按钮区域",
    remarkEn: "Custom footer actions" },
];
