import { EventItem, PropItem, SlotItem } from "../../.vitepress/components/api-block/src/types";

export const triggerProps: PropItem[] = [
  { name: "v-model", remark: "控制弹出层是否可见",
    remarkEn: "Controls popup visibility", type: ["Boolean"], default: false },
  {
    name: "trigger",
    remark: "触发方式",
    remarkEn: "Trigger",
    type: ["TriggerType"],
    optional: ["click", "hover"],
    default: "click",
  },
  { name: "position", remark: "弹出位置，支持 12 种方向",
    remarkEn: "Popup position; supports 12 placements", type: ["TriggerPosition"], default: "bottom" },
  { name: "popup-offset", remark: "弹出层与触发元素的偏移距离",
    remarkEn: "Offset between popup and trigger", type: ["Number"], default: 0 },
  { name: "popup-translate", remark: "弹出层平移量 [x, y]",
    remarkEn: "Popup translate offset [x, y]", type: ["Array"], default: "[0, 0]" },
  { name: "auto-fit-width", remark: "弹出层是否自适应触发元素宽度",
    remarkEn: "Whether popup matches trigger width", type: ["Boolean"], default: false },
  { name: "transition", remark: "弹出层过渡动画名称",
    remarkEn: "Popup transition name", type: ["String"], default: "fade" },
  { name: "click-outside", remark: "点击弹出层外部是否关闭",
    remarkEn: "Whether clicking outside closes the popup", type: ["Boolean"], default: true },
  { name: "disabled", remark: "是否禁用触发",
    remarkEn: "Whether trigger is disabled", type: ["Boolean"], default: false },
  { name: "hide-trigger", remark: "是否隐藏触发元素",
    remarkEn: "Whether to hide the trigger element", type: ["Boolean"], default: false },
  { name: "update-at-scroll", remark: "滚动时是否更新弹出层位置",
    remarkEn: "Whether to update popup position on scroll", type: ["Boolean"], default: false },
  { name: "scroll-to-close", remark: "滚动时是否关闭弹出层",
    remarkEn: "Whether to close popup on scroll", type: ["Boolean"], default: false },
  { name: "auto-fix-position", remark: "是否自动修正弹出位置以适配窗口",
    remarkEn: "Whether to auto-fit popup position to the viewport", type: ["Boolean"], default: true },
  { name: "scroll-to-close-time", remark: "滚动关闭的延迟时间（毫秒）",
    remarkEn: "Delay before closing on scroll (ms)", type: ["Number"], default: 400 },
  { name: "throttle-time", remark: "resize/scroll 事件节流时间（毫秒）",
    remarkEn: "Throttle for resize/scroll events (ms)", type: ["Number"], default: 20 },
  { name: "open-delay", remark: "悬停触发的延迟打开时间（毫秒）",
    remarkEn: "Hover open delay (ms)", type: ["Number"], default: 0 },
  { name: "close-delay", remark: "悬停触发的延迟关闭时间（毫秒）",
    remarkEn: "Hover close delay (ms)", type: ["Number"], default: 100 },
  { name: "boundary-padding", remark: "弹出层与窗口边界的最小留白",
    remarkEn: "Minimum margin from viewport edges", type: ["Number"], default: 8 },
  { name: "show-arrow", remark: "是否显示指向触发元素的箭头",
    remarkEn: "Whether to show an arrow pointing to the trigger", type: ["Boolean"], default: false },
  { name: "get-popup-container", remark: "自定义弹出层挂载容器",
    remarkEn: "Custom popup mount container", type: ["Function"] },
];

export const triggerEvents: EventItem[] = [
  { name: "update:modelValue", remark: "弹出层可见状态变化时触发",
    remarkEn: "Triggered when popup visibility changes", params: "visible: boolean" },
  { name: "popupVisible", remark: "弹出层显示/隐藏时触发",
    remarkEn: "Triggered when popup shows or hides", params: "visible: boolean" },
  { name: "positionChange", remark: "弹出层位置变化时触发",
    remarkEn: "Triggered when popup position changes", params: "{ position, top, left, width }" },
];

export const triggerSlots: SlotItem[] = [
  { name: "default", remark: "触发弹出层的元素",
    remarkEn: "Element that triggers the popup" },
  { name: "content", remark: "弹出层内容",
    remarkEn: "Popup content" },
];
